# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6df948f0487c5af467af502674f2ca44aaf00a682d9aaa9601b9a86fe750e272ae5d70e4a3cbe16ebf09e7e179e0465704b69ada093e9f1fd16803b6215a2b78

test:
  secret_key_base: 312fec98f44300fe34a2fda77b2131e39b11b0d07467c607716e8323bd12fea72dd3c806307075f583391b704d2e1d0e3aa6bcea48c13b19f07c1709921e5b25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
